packages:
  - rest-api
  - examples

catalog:
  '@allbridge/bridge-core-sdk': 3.31.0-alpha.2
  '@mysten/sui': ^1.21.2
  '@solana/web3.js': ^1.98.0
  '@stellar/stellar-sdk': ^15.0.1
  '@types/big.js': ^6.2.2
  '@typescript-eslint/eslint-plugin': ^8.18.1
  '@typescript-eslint/parser': ^8.18.1
  axios: ^1.15.0
  big.js: ^6.2.2
  bs58: ^6.0.0
  dotenv: ^16.4.7
  eslint: latest
  eslint-config-prettier: latest
  eslint-plugin-prettier: latest
  ethers: ^6.15.0
  prettier: ^3.4.2
  tronweb: 6.0.4
  web3-core: ^4.7.1

shared-workspace-lockfile: true
