packages:
  - 'rest-api'
  - 'examples'
shared-workspace-lockfile: true

catalog:
  '@solana/web3.js': ^1.98.0
  '@stellar/stellar-sdk': ^13.1.0
  'axios': ^1.7.9
  '@types/big.js': ^6.2.2
  'big.js': ^6.2.2
  'src': ^1.1.2
  'tronweb': ^6.0.0
  'web3': ^4.16.0
  'web3-core': ^4.7.1
  'web3-eth-contract': ^4.7.2
  '@typescript-eslint/eslint-plugin': ^8.18.1
  '@typescript-eslint/parser': ^8.18.1
  'bs58': ^6.0.0
  'dotenv': ^16.4.7
  'eslint': ^9.17.0
  'eslint-config-prettier': ^9.1.0
  'eslint-plugin-prettier': ^5.2.1
  'prettier': ^3.4.2